main: me.rayzr522.blockdelay.BlockDelay
name: BlockDelay
version: 1.0.0
description: A toggleable delay for placing blocks.
author: Rayzr
commands:
  blockdelay:
    description: Toggles the delay for placing blocks
    usage: "\u00A7cRayzr fracked something up."